# Exported from Render on 2025-12-02T15:33:11Z
version: "1"
projects:
- name: My project
  environments:
  - name: Production
    services:
    - type: web
      name: discord-bot-1-damp
      runtime: python
      repo: https://github.com/gh0st-2202/discord-bot-1-damp
      plan: free
      envVars:
      - key: .env
        sync: false
      region: oregon
      buildCommand: pip install -r requirements.txt
      startCommand: python main-bot.py
      autoDeployTrigger: commit
